---
- name: Gather facts and output resulting variables
  gather_facts: true
  hosts: all
  tasks:
  - name: Ensure facts gathered
    ansible.builtin.setup:

- name: Output variables gathered
  gather_facts: false
  hosts: kss_host
  tasks:
  # - name: Print all facts
  #   ansible.builtin.debug:
  #     var: ansible_facts
  - name: Dump hostvars
    ansible.builtin.debug:
      var: hostvars
...
