---
host_private_client_cert_cert_content: "{{ vault_private_client_cert_cert_content }}"
host_private_client_cert_cert_file: "{{ vault_private_client_cert_cert_file }}"
host_private_client_cert_key_content: "{{ vault_private_client_cert_key_content }}"
host_private_client_cert_key_file: "{{ vault_private_client_cert_key_file }}"
host_public_cert_full_file: "{{ vault_public_cert_full_file }}"
# host_public_cert_cert_file: "{{ vault_public_cert_cert_file }}"
# host_public_cert_key_file: "{{ vault_public_cert_key_file }}"
# host_public_cert_private_key: "{{ vault_public_cert_private_key }}"
...
