---
host_ansible_ssh_port: "{{ vault_ansible_ssh_port }}"
host_email_interfaces: "{{ vault_email_interfaces }}"
host_email_relayhost: "{{ vault_email_relayhost }}"
host_libvirt_pool_base_images: "{{ vault_libvirt_pool_base_images }}"
host_libvirt_pool_base_images_path: "{{ vault_libvirt_pool_base_images_path }}"
host_libvirt_pool_cloud_init: "{{ vault_libvirt_pool_cloud_init }}"
host_libvirt_pool_cloud_init_path: "{{ vault_libvirt_pool_cloud_init_path }}"
host_libvirtd_pool_list: "{{ vault_libvirtd_pool_list }}"
host_local_ipv6_cidr: "{{ vault_local_ipv6_cidr }}"
host_local_ipv6_gateway: "{{ vault_local_ipv6_gateway }}"
host_private_client_cert_cert_content: "{{ vault_private_client_cert_content }}"
host_private_client_cert_cert_file: "{{ vault_private_client_cert_cert_file }}"
host_private_client_cert_key_content: "{{ vault_private_client_cert_key_content }}"
host_private_client_cert_key_file: "{{ vault_private_client_cert_key_file }}"
host_second_interface: "{{ vault_second_interface }}"
host_storage_extra_use_lvm2: "{{ vault_storage_extra_use_lvm2 }}"
host_storage_filesystems: "{{ vault_storage_filesystems }}"
host_storage_logical_volumes: "{{ vault_storage_logical_volumes }}"
host_storage_mountpoints: "{{ vault_storage_mountpoints }}"
host_storage_mounts: "{{ vault_storage_mounts }}"
host_storage_volume_groups: "{{ vault_storage_volume_groups }}"
host_ups_name: "{{ vault_ups_name }}"
host_upsd_host: "{{ vault_upsd_host }}"
host_upsd_password: "{{ vault_upsd_password }}"
host_upsd_user: "{{ vault_upsd_user }}"
host_upsmon_type: "{{ vault_upsmon_type }}"
host_vbridge: "{{ vault_vbridge }}"
...
