---
- name: Ensure our unattended-upgrades package and suggests are present
  become: yes
  ansible.builtin.apt:
    name:
    - powermgmt-base
    - python3-gi
    - unattended-upgrades
    state: present
- name: Configure unattended-upgrades
  become: yes
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    group: root
    mode: "0644"
    owner: root
    src: 50unattended-upgrades
...
