---
admin_base_homedir: "{{ vault_admin_base_homedir }}"
admin_gecos: "{{ vault_admin_gecos }}"
admin_password: "{{ vault_admin_password }}"
admin_ssh_key: "{{ vault_admin_ssh_key }}"
admin_ssh_key_userdata: "{{ vault_admin_ssh_key_userdata }}"
admin_user: "{{ vault_admin_user }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
ansible_ssh_common_args: "{% if 'external_ssh' not in group_names %}-o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -p {{ bastion_port }} -W %h:%p -q {{ bastion_user }}@{{ bastion_host }}\"{% endif %}"
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
bastion_host: "{{ vault_bastion_host }}"
bastion_port: "{{ vault_bastion_port }}"
bastion_ssh_key: "{{ vault_bastion_ssh_key }}"
bastion_user: "{{ vault_bastion_user }}"
central_external_domain: "{{ vault_central_external_domain }}"
central_external_email: "{{ vault_central_external_email }}"
central_internal_domain: "{{ vault_central_internal_domain }}"
central_internal_email: "{{ vault_central_internal_email }}"

fallback_dns: "{{ vault_env_conn_admin[envname]['fallback_dns'] }}"
internal_relay_port: "{{ vault_env_conn_admin[envname]['internal_relay_port'] }}"
libvirt_client_ssh_key: "{{ vault_env_conn_admin[envname]['libvirt_client_ssh_key'] }}"
libvirt_client_user: "{{ vault_env_conn_admin[envname]['libvirt_client_user'] }}"
local_freshclam_mirror: "{{ vault_env_conn_admin[envname]['local_freshclam_mirror'] }}"
mail_local_destinations: "{{ default_mail_local_destinations }}"
opendkim_private_key: "{{ vault_env_conn_admin[envname]['opendkim_private_key'] | default(None) }}"
remote_admin_ip: "{{ vault_env_conn_admin[envname]['remote_admin_ip'] }}"
remote_ignore_ips: "{{ remote_admin_ip }}{% if remote_monitoring_ips is defined %} {{ remote_monitoring_ips }}{% endif %}"
remote_monitoring_ips: "{{ vault_env_conn_admin[envname]['remote_monitoring_ips'] }}"
v6natnet_ula: "{{ vault_env_conn_admin[envname]['v6natnet_ula'] }}"
...
