---
- name: Refresh list of volumes in base-images pool
  become: yes
  ansible.builtin.command: virsh pool-refresh {{ libvirt_pool_base_images | quote }}
- name: Refresh list of volumes in default pool
  become: yes
  ansible.builtin.command: virsh pool-refresh default
- name: Refresh list of volumes in fast pool
  become: yes
  ansible.builtin.command: virsh pool-refresh fast
- name: Refresh list of volumes in slow pool
  become: yes
  ansible.builtin.command: virsh pool-refresh slow
- name: Refresh list of volumes in pool containing cloud-init images
  become: yes
  ansible.builtin.command: virsh pool-refresh {{ libvirt_pool_cloud_init | quote }}
- name: Format nocloud image
  listen: Copy cloud init data to nocloud image
  loop: "{{ nocloud_img_size.results }}"
  loop_control:
    label: "{{ item.path }}"
  community.general.filesystem:
    dev: "{{ item.path }}"
    force: true
    fstype: vfat
    opts: -n CIDATA
    state: present
- name: Copy files to nocloud image
  listen: Copy cloud init data to nocloud image
  loop: "{{ nocloud_img_size.results }}"
  loop_control:
    label: "{{ item.path }}"
  ansible.builtin.command:
    argv:
    - mcopy
    - -oi
    - nocloud.img
    - user-data
    - meta-data
    - "::"
    chdir: "{{ item.path | dirname }}"
...
